name: RickyKhoo
favicon: null
layout_spectrum: 0.26353
typography_spectrum: 0.52806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#100d08'
    - '#a3603e'
    - '#4c4034'
    - '#f73835'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
