name: RickyKhoo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#100d08'
    - '#a3603e'
    - '#4c4034'
    - '#f73835'
  brandStrength: 0.5545089382212609
  lightness: 0.559141406789422
  saturation: 0.09703441895544529
  rhythmicContrast: 0.19677748437970877
purpose: []
